# Generated by Django 4.1 on 2022-08-09 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsLetter',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=191, unique=True)),
                ('description', models.TextField(max_length=2000, null=True)),
                ('slug', models.SlugField(unique=True)),
                ('sender_name', models.CharField(max_length=191, null=True)),
                ('sender_email', models.EmailField(max_length=191, null=True)),
                ('sender_reply_to', models.CharField(choices=[('newsletter', 'Newsletter'), ('support', 'Support')], default='newsletter', max_length=191)),
                ('status', models.CharField(choices=[('active', 'Active'), ('archived', 'Archived')], default='active', max_length=10)),
                ('visibility', models.CharField(default='members', max_length=50)),
                ('subscribe_on_signup', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('show_header_title', models.BooleanField(default=True)),
                ('title_font_category', models.CharField(choices=[('center', 'Center'), ('left', 'Left')], default='center', max_length=191)),
                ('show_feature_image', models.BooleanField(default=True)),
                ('body_font_category', models.CharField(choices=[('serif', 'Serif'), ('sans_serif', 'Sans Serif')], default='sans_serif', max_length=191)),
                ('footer_content', models.CharField(max_length=1000000000, null=True)),
                ('show_badge', models.BooleanField(default=True)),
                ('show_header_name', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField(null=True)),
            ],
        ),
    ]
