# Generated by Django 4.1 on 2022-08-09 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsletter',
            name='footer_content',
            field=models.TextField(max_length=1000000000, null=True),
        ),
    ]
