# Generated by Django 4.1 on 2022-08-09 13:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_newsletter_footer_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=2000)),
                ('slug', models.SlugField(max_length=191)),
                ('mobiledoc', models.TextField(max_length=1000000000, null=True)),
                ('html', models.TextField(max_length=1000000000, null=True)),
                ('comment_id', models.CharField(max_length=50, null=True)),
                ('plaintext', models.TextField(max_length=1000000000, null=True)),
                ('feature_image', models.CharField(max_length=2000, null=True)),
                ('featured', models.BooleanField(default=False)),
                ('type_name', models.CharField(choices=[('post', 'Post'), ('page', 'Page')], default='post', max_length=50)),
                ('status', models.CharField(default='draft', max_length=50)),
                ('locale', models.CharField(max_length=6, null=True)),
                ('visibility', models.CharField(default='public', max_length=50)),
                ('email_recipient_filter', models.TextField(max_length=1000000000)),
                ('created_at', models.DateTimeField()),
                ('created_by', models.CharField(max_length=24)),
                ('updated_at', models.DateTimeField(null=True)),
                ('updated_by', models.CharField(max_length=24, null=True)),
                ('published_at', models.DateTimeField(null=True)),
                ('published_by', models.CharField(max_length=24, null=True)),
                ('custom_excerpt', models.CharField(max_length=2000, null=True)),
                ('codeinjection_head', models.CharField(max_length=65535, null=True)),
                ('codeinjection_foot', models.CharField(max_length=65535, null=True)),
                ('custom_template', models.CharField(max_length=100, null=True)),
                ('canonical_url', models.URLField(max_length=2000, null=True)),
                ('newsletter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.newsletter')),
            ],
        ),
    ]
