# Generated by Django 4.1 on 2022-08-09 13:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostMeta',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('og_image', models.CharField(max_length=2000, null=True)),
                ('og_title', models.CharField(max_length=300, null=True)),
                ('og_description', models.CharField(max_length=500, null=True)),
                ('twitter_image', models.CharField(max_length=2000, null=True)),
                ('twitter_title', models.CharField(max_length=300, null=True)),
                ('twitter_description', models.CharField(max_length=500, null=True)),
                ('meta_title', models.CharField(max_length=500, null=True)),
                ('meta_description', models.CharField(max_length=2000, null=True)),
                ('email_subject', models.CharField(max_length=300, null=True)),
                ('frontmatter', models.TextField(max_length=65535, null=True)),
                ('feature_image_alt', models.CharField(max_length=191, null=True)),
                ('feature_image_caption', models.TextField(max_length=65535, null=True)),
                ('email_only', models.BooleanField(default=False)),
                ('post', models.OneToOneField(max_length=24, on_delete=django.db.models.deletion.CASCADE, to='blog.post')),
            ],
        ),
    ]
