# Generated by Django 4.1 on 2023-10-04 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_tag_alter_post_options_post_is_published_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='is_published',
        ),
        migrations.AddField(
            model_name='post',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='cover_image'),
        ),
        migrations.AddField(
            model_name='post',
            name='language',
            field=models.CharField(default='english', max_length=25, verbose_name='language'),
        ),
        migrations.AddField(
            model_name='post',
            name='meta_title',
            field=models.CharField(max_length=255, null=True, verbose_name='meta_title'),
        ),
        migrations.AddField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('PR', 'Private'), ('PU', 'Public'), ('UN', 'Unlisted'), ('DR', 'Draft')], default='PR', max_length=2, verbose_name='status'),
        ),
        migrations.CreateModel(
            name='PostReaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reaction', models.IntegerField(choices=[(1, 'Like'), (2, 'Love'), (3, 'Haha'), (4, 'Wow'), (5, 'Sad'), (6, 'Angry')])),
                ('post', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='blog.post')),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='blog.profile')),
            ],
        ),
        migrations.CreateModel(
            name='PostComment',
            fields=[
                ('created_at', models.DateTimeField(auto_created=True, auto_now=True, verbose_name='created_at')),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('content', models.TextField(verbose_name='content')),
                ('post', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='blog.post')),
            ],
        ),
    ]
